name: library_system
description: A new Flutter project.

publish_to: "none"
version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter


  firebase_auth: null
  cloud_firestore: ^0.13.4+2
  firebase_database: ^3.1.6
  firebase_core: ^0.4.5

  cupertino_icons: ^0.1.3
  custom_splash: ^0.0.2
  splashscreen: ^1.2.0
  barcode_scan: ^1.0.0
  uuid: ^2.2.2
  fluttertoast: ^7.1.1
  barcode: ^1.17.0
  flutter_svg: ^0.19.0
  

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - assets/images/
